### ISSUE TITLE
Feature Request: Ability to start at login

### ISSUE THREAD

**Issue by milojennings** [thesyntaxinator/TouchGuard#2]
I find this script really handy, but it's a bit of pain to have to remember to fire up a terminal and get it going every time I restart. It's also a bit bothersome cluttering up my windows with an open terminal session. 

Is there an easy way to make this start and run on login every time my computer boots up?

**Comment by amanagr** [comment]
@milojennings you can lake a look at https://github.com/amanagr/TouchGuard.
