### ISSUE TITLE
Feature Request: How to make this autostart with MacOS Sonoma?

### ISSUE THREAD

**Issue by swealpha** [thesyntaxinator/TouchGuard#6]
Hello!

Is it possible to make this script autostart with sonoma in a easy way? That would be amazing.

Wish you a happy day.

**Comment by thesyntaxinator** [comment]
Try https://github.com/thesyntaxinator/TouchGuard-1/tree/fix-for-later-macos and see if that works. If so, feel free to close this issue

**Comment by swealpha** [comment]
Hello! Thank you very much for your reply. I tested it but it didnt work.

I did exactly like the manual on the link https://github.com/thesyntaxinator/TouchGuard-1/blob/fix-for-later-macos/README.md

Is it possible to send you money as a small gift because this is a life saver for me if it works to autostart.

Wish you a great day.

**Comment by thesyntaxinator** [comment]
What was the error you got?

Feel free to Venmo [@Prag-Bat](https://venmo.com/u/Prag-Bat) if you would like

**Comment by swealpha** [comment]
Fixed it, you can read here! Thank you.
https://github.com/thesyntaxinator/TouchGuard/issues/7
